# Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: <% if(data['config-db']) { %>db-<% } else if(data['config-server']) { %>server-<% } else if(data['config-client']) { %>client-<% } %><%= data['config-name'] %>-config-map
data:<% for(const value of data['config-values']) { %>
  <%= value %><% } %>
