# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-server']) { %>server-<% } else if(data['deployment-client']) { %>client-<% } %><%= data['deployment-name'] %>-deployment
spec:
  replicas: <%= data['deployment-replicas'] %>
  selector:
    matchLabels:
      component: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-server']) { %>server-<% } else if(data['deployment-client']) { %>client-<% } %><%= data['deployment-name'] %>
  template:
    metadata:
      labels:
        component: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-server']) { %>server-<% } else if(data['deployment-client']) { %>client-<% } %><%= data['deployment-name'] %>
    spec:
      containers:
        - name: <%= data['deployment-name'] %>
          image: <%= data['deployment-image'] %><% if(data['deployment-ports'].length > 0) { %>
          ports:<% for(const port of data['deployment-ports']) { %>
            - containerPort: <%= port -%><% } %><% } %><% if(data['deployment-db'] && data['deployment-db-mysql']) { %>
          args:
            - --lower_case_table_names=1<% } %>
          resources:
            requests:
              memory: '100Mi'
              cpu: '50m'
            limits:
              memory: '200Mi'
              cpu: '100m'<% if(data['deployment-db'] || data['deployment-server']) { %>
          envFrom:
            - configMapRef:
                name: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-server']) { %>server-<% } %><%= data['deployment-name'] %>-config-map
            - secretRef:
                name: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-server']) { %>server-<% } %><%= data['deployment-name'] %>-secret <% } %> <% if(data['deployment-ports'].length > 0) { %>
          livenessProbe:
            tcpSocket:
              port: <%= data['deployment-ports'][0] %>
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: <%= data['deployment-ports'][0] %>
            initialDelaySeconds: 5
            timeoutSeconds: 1 <% } %> <% if(data['deployment-db'] || data['deployment-client']) { %>
          volumeMounts:
            - name: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-client']) { %>client-<% } %><%= data['deployment-name'] %><% if(data['deployment-db']) { %>-persistent-storage<% } else if(data['deployment-client']) { %>-env<% } %> <% if(data['deployment-db']) { %>
              mountPath: /var/lib/mysql
              subPath: mysql <% } else if(data['deployment-client']) { %>
              mountPath: /usr/local/apache2/htdocs/assets/.env
              subPath: .env <% } %>
      volumes:
        - name: <% if(data['deployment-db']) { %>db-<% } else if(data['deployment-client']) { %>client-<% } %><%= data['deployment-name'] %><% if(data['deployment-db']) { %>-persistent-storage<% } else if(data['deployment-client']) { %>-env<% } %> <% if(data['deployment-db']) { %>
          persistentVolumeClaim:
            claimName: db-<%= data['deployment-name'] %>-persistent-volume-claim <% } else if(data['deployment-client']) { %>
          configMap:
            name: client-<%= data['deployment-name'] %>-config-map <% } %> <% } %>
