# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <%= data['ingress-name'] %>
  namespace: <%= data['global-namespace'] %>
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: <%= data['ingress-name'] %>
    hosts:<% for(const url of data['ingress-urls']) { %>
    - <%= url -%><% } %>
  rules:<% for(const url of data['ingress-urls']) { %>
  - host: <%= url %>
    http:
      paths:
      - backend:
          serviceName: <%= data['ingress-name'] %>
          servicePort: 80<% } %>
