# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <% if(data['pvc-db']) { %>db-<% } else if(data['pvc-server']) { %>server-<% } %><%= data['pvc-name'] %>-persistent-volume-claim
spec:
  selector:
    matchLabels:
      component: <% if(data['pvc-db']) { %>db-<% } else if(data['pvc-server']) { %>server-<% } %><%= data['pvc-name'] %>-persistent-volume
  storageClassName: local-storage
  accessModes:
    - <%= data['pvc-access-mode'] %>
  resources:
    requests:
      storage: <%= data['pvc-size'] %>
