# Secret
apiVersion: v1
kind: Secret
metadata:
  name: <% if(data['secret-db']) { %>db-<% } else if(data['secret-server']) { %>server-<% } %><%= data['secret-name'] %>-secret
data:<% for(const value of data['secret-values']) { %>
  <%= value %><% } %>
