# Secret
apiVersion: v1
kind: Secret
metadata:
  name: <%= data['secret-name'] %>
  namespace: <%= data['global-namespace'] %><% if(data['global-app-name'] || data['global-app-tier']) { %>
  labels:<% if(data['global-app-name']) { %>
    app: <%= data['global-app-name'] -%><% } %><% if(data['global-app-tier']) { %>
    tier: <%= data['global-app-tier'] -%><% } %><% } %>
data:<% for(const value of data['secret-values']) { %>
  <%= value %><% } %>
