# Service
apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_PATH_SLUG}
  namespace: ${NAMESPACE}
  labels:
    app: ${CI_PROJECT_PATH_SLUG}
    tier: web
spec:
  selector:
    name: ${CI_PROJECT_PATH_SLUG}
    app: ${CI_PROJECT_PATH_SLUG}
    tier: web
  ports:
    - name: http
      port: 80
      targetPort: http
