# Service-ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: <% if(data['service-db']) { %>db-<% } else if(data['service-server']) { %>server-<% } else if(data['service-client']) { %>client-<% } %><%= data['service-name'] %>-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: <% if(data['service-db']) { %>db-<% } else if(data['service-server']) { %>server-<% } else if(data['service-client']) { %>client-<% } %><%= data['service-name'] %>
  ports:
    - port: <%= data['service-port'] %>
      targetPort: <%= data['service-port'] %>
